# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 546f425de9d9c5b00f15de3d30a0fabb637c17ef9b28dd21935f781be2d974648f464c7c7b1d27bfb8327894a72c83c882badfd42b90a2ba46fe43e5212022bf

test:
  secret_key_base: 3bab79ed4f1668ad5eaeb404b869efdd0ede3e194c575fe64d6cab24b6346fb74c89dffcceb096ef21963cbb907fcc620523a8d5141bf3acd51065723b78a6e6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
